config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords'
  }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'public/homes#top'

  namespace :admin do
    get "/"=>"homes#top"
    get "user_search" => "searches#user_search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :menus, only: [:index, :show, :destroy] do
       resources :comments, only: [:destroy]
    end
  end


  namespace :public do
    get "search" => "searches#search"
    resources :users do
      member do
        get :likes
      end
    end
    get "new_arrival" => "menus#new_arrival"
    resources :menus do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  validates :comment, presence: true, length: { maximum: 75 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :menu
  belongs_to :user
  validates_uniqueness_of :menu_id, scope: :user_id
end

app/models/menu.rb
class Menu < ApplicationRecord
   has_one_attached :image
   belongs_to :user
   has_many :menu_tags, dependent: :destroy
   has_many :tags, through: :menu_tags, dependent: :destroy
   has_many :likes, dependent: :destroy
   has_many :liked_users, through: :likes, source: :user
   has_many :comments, dependent: :destroy

   validates :comment, presence: true, length: { maximum: 13 }
   validates :start_time, presence: true

  #画像表示
  def get_image
   unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage-photo.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
      image
  end

  #検索
  def self.looks(word)
      @menu = Menu.where("menu_name_1 LIKE? OR food_detail_1 like? OR menu_name_2 LIKE?
      OR food_detail_2 like? OR menu_name_3 LIKE? OR food_detail_3 like? OR menu_name_4 LIKE? OR food_detail_4 like?
      OR menu_name_5 LIKE? OR food_detail_5 like? OR menu_name_6 LIKE? OR food_detail_6 like? OR menu_name_7 LIKE? OR food_detail_7 like?
      OR menu_name_8 LIKE? OR food_detail_8 like?","%#{word}%", "%#{word}%","%#{word}%","%#{word}%","%#{word}%",
      "%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%")
  end
end

app/models/menu_tag.rb
class MenuTag < ApplicationRecord
  belongs_to :menu
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :menu_tags
  has_many :menus, through: :menu_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :menus, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_menus, through: :likes, source: :menu
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true

#ゲストログイン
  def self.guest
      find_or_create_by!(name: 'guestuser' ,email: 'guestusers@gmail.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
  end

#画像
  def get_profile_image(width, height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end

#いいね
  def liked_by?(menu_id)
    likes.where(menu_id: menu_id).exists?
  end

#user検索
  def self.looks(word)
    @user = User.where("name LIKE?","#{word}")
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
    @comments = @menu.comments
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    flash[:alert] = "投稿を削除しました。"
    redirect_to admin_menus_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %>件のエラーが発生しました
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kondatenikki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
　  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
　  <script src="https://kit.fontawesome.com/0362e50478.js" crossorigin="anonymous"></script>
  </head>



  <body>
    <!--ヘッダー上-->
    <header>
     <nav class="navbar navbar-expand-sm navbar-light color" >
      <div class="container">
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>

       <!--ロゴ-->
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="float-left header-logo mt-3">
            <%= link_to root_path do %>
              <div class="logo" href="/"><%= image_tag('logo_4.png')%></div>
            <% end %>
        </div>


       <!--ヘッダーナビ-->
        <ul class="navbar-nav ml-auto">
         <% if user_signed_in? %>
             <li>
               <%= link_to "投稿する", new_public_menu_path, class: "btn btn-outline-dark mr-3" %>
             </li>
             <li>
               <%= link_to "日記", public_menus_path, class: "btn btn-outline-dark mr-3" %>
             </li>
             <li>
               <%= link_to "マイページ", public_user_path(current_user), class: "btn btn-outline-dark mr-3" %>
             </li>
             <li>
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark mr-3" %>
             </li>
       　 <% elsif admin_signed_in? %>
             <li>
              <%= link_to "管理者TOP", admin_path, class:"btn btn-outline-dark mr-3" %>
             </li>
             <li>
              <%= link_to "投稿一覧", admin_menus_path, class:"btn btn-outline-dark mr-3" %>
             </li>
             <li>
               <%= link_to "ユーザー一覧", admin_users_path, class:"btn btn-outline-dark mr-3" %>
             </li>
             <li>
               <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark mr-3" %>
             </li>
       　 <% else %>
             <li>
               <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-dark mr-3" %>
             </li>
             <li>
               <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-dark mr-3" %>
             </li>
        <% end %>
        </ul>
       </div>
      </div>
     </nav>
    </header>

    <!--ヘッダー下管理者側では表示しない-->
    <div class="second-header pt-1 pb-2">
     <% if !admin_signed_in? %>
        <div class="container mt-3">
          <div class="row">
              <!--タグ-->
              <div class="col-md-6">
                  <%= form_tag  public_search_path, method: :get, class: 'boards__searchForm text-center' do %>
                      <%= select_tag :tag_id,
                         options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                         {
                           prompt: 'タグで絞り込み検索',
                           onchange: 'submit(this.form);'
                         }
                       %>
                　<% end %>
              </div>
              <!--フォーム検索-->
              <div class="col-md-6">
                  <div class="search_form text-right mr-5">
                    <%= form_with url: public_search_path, local: true, method: :get do |f| %>
                      <%= f.text_field :word, placeholder: "メニュー名、食材" %>
                      <%= f.submit "検索", class: "btn btn-sm btn-primary mb-1" %>
                    <% end %>
                  </div>
              </div>

          </div>
        </div>
     <% end %>
    </div>

   <main>
     <%= yield %>
   </main>

   <footer class="color text-light pt-3 pb-1">
        <p class="text-center"> © kondate nikki</p>
   </footer>

  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar mr-5 ml-5">
  <div class="calendar-heading text-center mt-3 mb-3">
     <%= link_to t('simple_calendar.previous', default: '<<先月'), calendar.url_for_previous_view %>
      <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></strong>
        <%= "#{Date.today.month}月" %>
        <%= link_to t('simple_calendar.next', default: '来月>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>