config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords'
  }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'public/homes#top'

  namespace :admin do
    get "/"=>"homes#top"
    get "user_search" => "searches#user_search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :menus, only: [:index, :show, :destroy] do
       resources :comments, only: [:destroy]
    end
  end


  namespace :public do
    get "search" => "searches#search"
    resources :users do
      member do
        get :likes
      end
    end
    get "new_arrival" => "menus#new_arrival"
    resources :menus do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :menus, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_menus, through: :likes, source: :menu
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true

#ゲストログイン
  def self.guest
      find_or_create_by!(name: 'guestuser' ,email: 'guestusers@gmail.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
  end

#画像
  def get_profile_image(width, height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end

#いいね
  def liked_by?(menu_id)
    likes.where(menu_id: menu_id).exists?
  end

#user検索
  def self.looks(word)
    @user = User.where("name LIKE?","#{word}")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(resource)
    public_user_path(current_user)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
    before_action :reject_user, only: [:create]

  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to public_user_path(current_user), notice: "guestuserでログインしました。"
  end

# 退会しているかを判断
  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.is_deleted) == true)
        flash[:alert] = "利用停止中です。"
        redirect_to new_user_session_path
      end
    else
        flash[:notice] = "項目を入力してください"
    end
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_user_index.html.erb
　<div class="row">
       <table class="col-md-12">
           <thead>
                  <tr>
                    <th>会員ID</th>
                    <th>氏名</th>
                    <th>メールアドレス</th>
                    <th>ステータス</th>
                  </tr>
           </thead>
    
           <tbody>
                <% users.each do |user| %>
                  <tr class="border">
                    <td><%= user.id %></td><br>
                    <td>
                        <%= link_to admin_user_path(user), class:"text-info" do %>
                          <%= user.name %>
                        <% end %>
                    </td><br>
                    <td><%= user.email %></td><br>
        
                   <!--利用停止にしているか-->
                    <% if user.is_deleted == true %>
                       <td class="text-secondary">使用停止</td>
                    <% else %>
                       <td class="text-success">有効</td>
                    <% end %>
                  </tr>
                <% end %>
           </tbody>
       </table>
  </div>

app/views/admin/users/edit.html.erb
<div class="container pb-5 mt-5">
  <div class="row pb-5">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>

      <div class="head mt-4 mb-3">
         <h2><strong><%= @user.name %>さんの登録情報編集</strong></h2>
      </div>
  
      <div class"row card">
         <div class="col-12 mt-4">
           <%= form_with model:@user, url:admin_user_path do |f| %>
             <div>
                  <%= f.label :"会員ID" %>
                  <%= @user.id %>
             </div>
             <div class="form-group">
                  <%= f.label :"ニックネーム" %><br>
                  <%= f.text_field :name %>
             </div>
             <div class="form-group">
                  <%= f.label :"メールアドレス" %><br>
                  <%= f.email_field :email, class:"col-12" %>
             </div>
             <div class="form-group">
                  <%= f.label :"会員ステータス" %>
                  <%= f.radio_button :is_deleted, true %>
                  <%= f.label :is_deleted, "利用停止",{value: :true, style: "display: inline-block;"} %>
                  <%= f.radio_button :is_deleted, false %>
                  <%= f.label :is_deleted, "有効",{value: :false, style: "display: inline-block;"} %>
             </div>
  
           <div class"row">
             <div class="col mt-4 text-right">
                 <%= f.submit "編集内容を保存", class:"btn btn-success" %>
                 <% end %>
             </div>
             <div>
                 <%= link_to admin_users_path, class:"btn btn-outline-info" do %>
                   <i class="fa-solid fa-arrow-left"></i>
                 <% end %>
             </div>
           </div>
         </div>
      </div>
      
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class='container pb-5 mt-3'>
  
  <h2>ユーザー一覧</h2>
  <!--ユーザー検索-->
  <div class="search_form">
    <%= form_with url: admin_user_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
  <!--ユーザー一覧-->
  <%= render "admin/users/user_index", users: @users %>

</div>

app/views/admin/users/show.html.erb
<div class="container pb-5">
  <div class="row pb-5">
    <div class='col-md-12 pb-5'>
      <div class="row">
       <div class="col-md-8 pr-2 pl-2 mx-auto">

          <div class="head mt-5 mb-5">
            <h2><strong><%= @user.name %>さんの登録情報</strong></h2>
          </div>
  
          <table class="table">
            <thead>
              <tr>
                <th>会員ID</th>
                <th><%= @user.id %></th>
              </tr>
  
              <tr>
                <th>ニックネーム</th>
                <th><%= @user.name %></th>
              </tr>
  
              <tr>
                <th>メールアドレス</th>
                <th><%= @user.email %></th>
              </tr>
  
              <tr>
                <th>会員ステータス</th>
                 <% if @user.is_deleted == true %>
                   <th class="text-danger">利用停止中</th>
                 <% else %>
                   <th class="text-success">有効</th>
                 <% end %>
              </tr>
            </thead>
          </table>
  
          <div class="row mt-4">
            <div class="col-8">
              <!--編集画面へ-->
            　<%= link_to edit_admin_user_path, class:"btn btn-outline-success" do %>
            　   <i class="fa-solid fa-pen-to-square"></i>
            　<% end %>
            </div>
  
            <div>
              <!--一覧画面へ-->
              <%= link_to admin_users_path, class:"btn btn-outline-info" do %>
                <i class="fa-solid fa-arrow-left"></i>
              <% end %>
            </div>
          </div>

  　     </div>
      </div>
    </div>
  </div>
</div>