config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords'
  }

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'public/homes#top'

  namespace :admin do
    get "/"=>"homes#top"
    get "user_search" => "searches#user_search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :menus, only: [:index, :show, :destroy] do
       resources :comments, only: [:destroy]
    end
  end


  namespace :public do
    get "search" => "searches#search"
    resources :users do
      member do
        get :likes
      end
    end
    get "new_arrival" => "menus#new_arrival"
    resources :menus do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  validates :comment, presence: true, length: { maximum: 75 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :menu
  belongs_to :user
  validates_uniqueness_of :menu_id, scope: :user_id
end

app/models/menu.rb
class Menu < ApplicationRecord
   has_one_attached :image
   belongs_to :user
   has_many :menu_tags, dependent: :destroy
   has_many :tags, through: :menu_tags, dependent: :destroy
   has_many :likes, dependent: :destroy
   has_many :liked_users, through: :likes, source: :user
   has_many :comments, dependent: :destroy

   validates :comment, presence: true, length: { maximum: 13 }
   validates :start_time, presence: true

  #画像表示
  def get_image
   unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage-photo.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
      image
  end

  #検索
  def self.looks(word)
      @menu = Menu.where("menu_name_1 LIKE? OR food_detail_1 like? OR menu_name_2 LIKE?
      OR food_detail_2 like? OR menu_name_3 LIKE? OR food_detail_3 like? OR menu_name_4 LIKE? OR food_detail_4 like?
      OR menu_name_5 LIKE? OR food_detail_5 like? OR menu_name_6 LIKE? OR food_detail_6 like? OR menu_name_7 LIKE? OR food_detail_7 like?
      OR menu_name_8 LIKE? OR food_detail_8 like?","%#{word}%", "%#{word}%","%#{word}%","%#{word}%","%#{word}%",
      "%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%","%#{word}%")
  end
end

app/models/menu_tag.rb
class MenuTag < ApplicationRecord
  belongs_to :menu
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :menu_tags
  has_many :menus, through: :menu_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :menus, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_menus, through: :likes, source: :menu
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true

#ゲストログイン
  def self.guest
      find_or_create_by!(name: 'guestuser' ,email: 'guestusers@gmail.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
  end

#画像
  def get_profile_image(width, height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end

#いいね
  def liked_by?(menu_id)
    likes.where(menu_id: menu_id).exists?
  end

#user検索
  def self.looks(word)
    @user = User.where("name LIKE?","#{word}")
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    Comment.find(params[:id]).destroy
    @menu = Menu.find(params[:menu_id])
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
    @comments = @menu.comments
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    flash[:alert] = "投稿を削除しました。"
    redirect_to admin_menus_path
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def user_search
    if params[:word].present?
     @users = User.looks(params[:word])
     @word = params[:word]
    else
     @users = User.all
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/comments/destroy.js.erb
$("#comment-index").html("<%= j(render "public/comments/comment", menu: @menu) %>")

app/views/admin/menus/index.html.erb
<div class="container pb-5 mt-4">
  <p class="text-danger"><%= flash[:alert] %></p>
  <h2><strong>投稿一覧</strong></h2>
    <div class="row ml-1">
      <%= render "public/searches/allsearch", menus: @menus %>
    </div>
</div>

app/views/admin/menus/show.html.erb
<div class="container pb-5">
  <div class="row">
    <div class="col-md-8 mt-4">
      <h2>投稿詳細</h2>
    </div>

    <div class="col-md-4 mt-4">
      <%= link_to "投稿削除",  admin_menu_path(@menu), method: :delete, class:"btn btn-sm btn-outline-danger" %>
    </div>
  </div>
  
  <!--ここから投稿表示-->
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @menu.get_image, size: '432x324', class:"post_img" %>
      <p><strong>一言コメント：<%= @menu.comment %></strong></p>
    </div>

    <div class="col-md-6 pb-5">
       <!--カラムに値が入っていれば表示-->
       <% if  @menu.menu_name_1.present? %>
         <p><strong>主食：<%= @menu.menu_name_1 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_1.present? %>
         <p>使用した食材(主食)：<%= @menu.food_detail_1 %></p>
       <% end %>

       <% if  @menu.menu_name_2.present? %>
         <p><strong>汁物：<%= @menu.menu_name_2 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_2.present? %>
         <p>使用した食材(汁物)：<%= @menu.food_detail_2 %></p>
       <% end %>

       <% if  @menu.menu_name_3.present? %>
         <p><strong>主菜：<%= @menu.menu_name_3 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_3.present? %>
         <p>使用した食材(主菜)：<%= @menu.food_detail_3 %></p>
       <% end %>

       <% if  @menu.menu_name_4.present? %>
         <p><strong>主菜2：<%= @menu.menu_name_4 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_4.present? %>
         <p>使用した食材(主菜2)：<%= @menu.food_detail_4 %></p>
       <% end %>

       <% if  @menu.menu_name_5.present? %>
         <p><strong>副菜：<%= @menu.menu_name_5 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_5.present? %>
         <p>使用した食材(副菜)：<%= @menu.food_detail_5 %></p>
       <% end %>

       <% if  @menu.menu_name_6.present? %>
         <p><strong>副菜2：<%= @menu.menu_name_6 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_6.present? %>
         <p>使用した食材(副菜2)：<%= @menu.food_detail_6 %></p>
       <% end %>

       <% if  @menu.menu_name_7.present? %>
         <p><strong>副菜3：<%= @menu.menu_name_7 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_7.present? %>
         <p>使用した食材(副菜3)：<%= @menu.food_detail_7 %></p>
       <% end %>

       <% if  @menu.menu_name_8.present? %>
         <p><strong>その他：<%= @menu.menu_name_8 %></strong></p>
       <% end %>
       <% if  @menu.food_detail_8.present? %>
         <p>使用した食材(その他)：<%= @menu.food_detail_8 %></p>
       <% end %>

       <p>作成日：<%= @menu.start_time.strftime('%Y/%m/%d') %></p>


       <!--コメント機能-->
       <div class="border-top">
         <h6 class="mt-3"><i class="fa-regular fa-comments"></i>コメント</h6>
          <table>
            <tbody id="comment-index" >
              <%= render "public/comments/comment", menu: @menu %>
            </tbody>
          </table>
       </div>
    </div>
  </div>
</div>

app/views/admin/searches/user_search.html.erb
<div class="container pb-5 mt-5">
  <h2>ユーザー検索結果 "<%= @word %>"</h2>
  <%= render "admin/users/user_index", users: @users %>
</div>